// <auto-generated />
using MiPrimerPrograma;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace MiPrimerPrograma.Migrations
{
    [DbContext(typeof(PrimerProgramaContext))]
    [Migration("20200426214557_Inicial")]
    partial class Inicial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.3");

            modelBuilder.Entity("MiPrimerPrograma.Localidad", b =>
                {
                    b.Property<int>("LocalidadId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("NombreLocalidad")
                        .HasColumnType("TEXT");

                    b.HasKey("LocalidadId");

                    b.ToTable("Localidades");
                });

            modelBuilder.Entity("MiPrimerPrograma.Persona", b =>
                {
                    b.Property<int>("PersonaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("LocalidadId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("NombrePersona")
                        .HasColumnType("TEXT");

                    b.HasKey("PersonaId");

                    b.HasIndex("LocalidadId");

                    b.ToTable("Personas");
                });

            modelBuilder.Entity("MiPrimerPrograma.Persona", b =>
                {
                    b.HasOne("MiPrimerPrograma.Localidad", "Localidad")
                        .WithMany("Personas")
                        .HasForeignKey("LocalidadId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
